from selenium import webdriver
import time

driver = webdriver.Chrome(executable_path="C:\\chromedriver.exe")
driver.get("https://login.salesforce.com/")
driver.maximize_window()
driver.find_element_by_css_selector("#username").send_keys("Ankush Deep")
driver.find_element_by_css_selector(".password").send_keys("anythingfromanywhere")
time.sleep(2)
driver.find_element_by_css_selector(".password").clear()
driver.find_element_by_link_text("Forgot Your Password?").click()
driver.find_element_by_xpath("//input[@value='Cancel']").click()
time.sleep(2)
print(driver.find_element_by_class_name("usernamelabel").text)
print(driver.find_element_by_xpath("//label[text()='Password']").text)
print(driver.find_element_by_xpath("//form[@name='login']/div[3]/label").text)
driver.find_element_by_link_text("Use Custom Domain").click()
time.sleep(2)
print(driver.find_element_by_xpath("//div[@id='mydomain_preview']").text)
driver.find_element_by_css_selector("button#hint_back_domain").click()
time.sleep(2)
driver.minimize_window()
time.sleep(2)
print("The code has been finished")
driver.close()
